CMD_ID = 'Batch3DPrint_Command'
CMD_NAME = 'Batch 3D Print'
CMD_DESCRIPTION = 'Batch export mesh files while incrementing a Fusion user parameter.'
WORKSPACE_ID = 'FusionSolidEnvironment'
PANEL_ID = 'MakePanel'
MANUAL_PARAMETER_KEY = '__manual_parameter__'
SELECT_PARAMETER_KEY = '__select_parameter__'

GEOMETRY_FILTERS = ('Bodies', 'Occurrences', 'RootComponents')

# Command input IDs.
GEOMETRY = 'geometry'
PARAM_SELECT = 'paramSelect'
PARAM_NAME = 'paramName'
PARAM_MODE = 'paramMode'
TEXT_FORMAT = 'textFormat'
START_VALUE = 'startValue'
INCREMENT = 'increment'
FILE_COUNT = 'fileCount'
EXPORT_FORMAT = 'exportFormat'
UNIT_TYPE = 'unitType'
REFINEMENT = 'refinement'
SURFACE_DEVIATION = 'surfaceDeviation'
NORMAL_DEVIATION = 'normalDeviation'
MAX_EDGE_LENGTH = 'maximumEdgeLength'
ASPECT_RATIO = 'aspectRatio'
ONE_FILE_PER_BODY = 'oneFilePerBody'
FILE_BASE = 'fileBase'
OUTPUT_PARENT_FOLDER = 'outputParentFolder'
BROWSE_FOLDER = 'browseFolder'
OUTPUT_FOLDER_PREVIEW = 'outputFolderPreview'
NOTES = 'notes'
